version: '3.8'

services:
  distributor:
    build:
      context: .
      dockerfile: apps/distributor/dockerfile
    container_name: distributor
    hostname: distributor
    networks:
      - peekaboo-network
    ports:
      - '6030:6030'
    env_file:
      - ./packages/common/config/.env

  master:
    build:
      context: .
      dockerfile: apps/game/master/dockerfile
    container_name: master
    hostname: master
    networks:
      - peekaboo-network
    ports:
      - '6050:6050'
    env_file:
      - ./packages/common/config/.env
    depends_on:
      - distributor

  lobby:
    build:
      context: .
      dockerfile: apps/lobby/dockerfile
    container_name: lobby
    hostname: lobby
    networks:
      - peekaboo-network
    ports:
      - '6010:6010'
    env_file:
      - ./packages/common/config/.env
    depends_on:
      - master

  account:
    build:
      context: .
      dockerfile: apps/account/dockerfile
    container_name: account
    hostname: account
    networks:
      - peekaboo-network
    ports:
      - '6020:6020'
    env_file:
      - ./packages/common/config/.env
    depends_on:
      - lobby

  session:
    build:
      context: .
      dockerfile: apps/session/dockerfile
    container_name: session
    hostname: session
    networks:
      - peekaboo-network
    ports:
      - '6040:6040'
    env_file:
      - ./packages/common/config/.env
    depends_on:
      - account

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/dockerfile
    container_name: gateway
    hostname: gateway
    networks:
      - peekaboo-network
    ports:
      - '6000:6000'
    env_file:
      - ./packages/common/config/.env
    depends_on:
      - session

networks:
  peekaboo-network:
    driver: bridge
